---
scenario:
  name: fedora
platforms:
  - name: fedora-30
    image: dokken/fedora-latest
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - sensu_checks
  - name: fedora-29
    image: dokken/fedora-29
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - sensu_checks
  - name: fedora-28
    image: dokken/fedora-28
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - sensu_checks
provisioner:
  inventory:
    host_vars:
      fedora-30:
        inspec_version: el7
      fedora-29:
        inspec_version: el7
      fedora-28:
        inspec_version: el7
