---
scenario:
  name: centos
platforms:
  - name: centos-6
    image: dokken/centos-6
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
  - name: centos-7
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      centos-6:
        inspec_version: el6
      centos-7:
        inspec_version: el7
