---
scenario:
  name: amazonlinux
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: True
platforms:
  - name: amazonlinux-1
    image: dokken/amazonlinux
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: amazonlinux-2
    image: dokken/amazonlinux-2
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default/playbook.yml
    verify: ../default/verify.yml
  lint:
    name: ansible-lint
    enabled: True
  inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        rabbitmq_server: true
        redis_server: true
        rabbitmq_host: "{{ ansible_hostname }}"
        redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
    host_vars:
      amazonlinux-1:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/el/6/inspec-2.1.68-1.el6.x86_64.rpm
        inspec_download_sha256sum: a62bc8d8ea803a72b7e834f5993c1d9eab50539293365a067cd29736daeb3fea
      amazonlinux-2:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/el/7/inspec-2.1.68-1.el7.x86_64.rpm
        inspec_download_sha256sum: 54fb2aab023a228c8f622653daabed14f2345780ec978670dbd262a63ad06fe9
verifier:
  name: inspec
  directory: ../default/tests/
  lint:
    name: rubocop
    enabled: true
