---
scenario:
  name: ubuntu
platforms:
  - name: ubuntu-14.04
    image: dokken/ubuntu-14.04
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
  - name: ubuntu-16.04
    image: dokken/ubuntu-16.04
    command: /bin/systemd
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-18.04
    image: dokken/ubuntu-18.04
    command: /bin/systemd
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      ubuntu-14.04:
        inspec_version: ubuntu1404
      ubuntu-16.04:
        inspec_version: ubuntu1604
      ubuntu-18.04:
        inspec_version: ubuntu1804
